-- create
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  dept TEXT NOT NULL,
  salary REAL NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Clark', 'Sales', 60000, '123 Elm St');
INSERT INTO EMPLOYEE VALUES (0002, 'Dave', 'Accounting', 55000, '456 Oak St');
INSERT INTO EMPLOYEE VALUES (0003, 'Ava', 'Sales', 62000, '789 Pine St');
INSERT INTO EMPLOYEE VALUES (0004, 'Eva', 'Accounting', 58000, '321 Maple St');
INSERT INTO EMPLOYEE VALUES (0005, 'Aywa', 'Sales', 63000, '654 Birch St');
INSERT INTO EMPLOYEE VALUES (0006, 'Seb', 'Bla bla', 70000, '987 Cedar St');

-- fetch 
SELECT * FROM EMPLOYEE WHERE dept = 'Sales';
SELECT * FROM EMPLOYEE WHERE dept = 'Accounting';
SELECT * FROM EMPLOYEE WHERE dept = 'Bla bla';